apiVersion: v1
kind: Pod
metadata:
  name: ms-resources
spec:
  # nodeName: aks-agentpool-22948950-vmss000003
  # nodeSelector:
  #   kubernetes.io/hostname: aks-agentpool-22948950-vmss000004
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions: 
          - key: kubernetes.io/hostname
            operator: In
            values:
            - aks-agentpool-22948950-vmss000003
        weight: 1
  containers:
  - image: nginx:latest
    name: nginx-container
    ports:
    - containerPort: 80
    # resources:
    #   limits:
    #     cpu: 2
    #     memory: 100Mi
    #   requests:
    #     cpu: 1
    #     memory: 50Mi